spring.application.name=backend
server.port=8090
app.jwt.secret=TjWnZr4u7x!A%D*G-KaPdSgVkXp2s5v8y/B?E(H+MbQeThWmZq4t7w9z$C&F)J@N
app.jwt.expiration=86400000
spring.profiles.active=dev

# =============================================
# Cloudinary
# =============================================
cloudinary.cloud_name=hu6f4dkq
cloudinary.api_key=584868457399837
cloudinary.api_secret=s3v1rGUuvNm7m-GfYzCUoB9qSi4
google.gemini.api-key=${GEMINI_API_KEY}
google.gemini.model=gemini-flash-lite-latest

# Límite máximo para un solo archivo (ej. 20 Megabytes)
spring.servlet.multipart.max-file-size=20MB

# Límite máximo para toda la petición junta (archivos + texto)
spring.servlet.multipart.max-request-size=25MB